# Generated by Django 4.1.13 on 2026-01-15 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for Review'), ('under_review', 'Under Review'), ('changes_requested', 'Changes Requested'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes not visible to borrower')),
                ('changes_requested', models.JSONField(blank=True, default=list, help_text='List of requested changes')),
                ('mobile_number', models.CharField(blank=True, max_length=30)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('consent_privacy', models.BooleanField(default=False)),
                ('consent_privacy_version', models.CharField(blank=True, max_length=50)),
                ('consent_privacy_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_terms', models.BooleanField(default=False)),
                ('consent_terms_version', models.CharField(blank=True, max_length=50)),
                ('consent_terms_timestamp', models.DateTimeField(blank=True, null=True)),
                ('consent_credit_search', models.BooleanField(default=False)),
                ('consent_credit_search_timestamp', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('trading_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address_1', models.CharField(blank=True, max_length=255)),
                ('address_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('experience_description', models.TextField(blank=True)),
                ('income_details', models.JSONField(blank=True, default=dict)),
                ('expenses_details', models.JSONField(blank=True, default=dict)),
                ('company_data', models.JSONField(blank=True, default=dict, help_text='Full Companies House data including charges summary')),
                ('company_verified_at', models.DateTimeField(blank=True, null=True)),
                ('charges_summary', models.JSONField(blank=True, default=dict, help_text='Summary of company charges (mortgages, debentures)')),
                ('trading_address', models.TextField(blank=True)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=30)),
                ('directors_data', models.JSONField(blank=True, default=list)),
                ('shareholders_data', models.JSONField(blank=True, default=list)),
                ('applicants_required', models.JSONField(blank=True, default=list)),
                ('applicants_data', models.JSONField(blank=True, default=list, help_text='Array of applicant objects')),
                ('financial_mode', models.CharField(choices=[('quick', 'Quick'), ('detailed', 'Detailed')], default='quick', max_length=20)),
                ('financial_data', models.JSONField(blank=True, default=dict)),
                ('bank_data_method', models.CharField(blank=True, choices=[('open_banking', 'Open Banking'), ('pdf_upload', 'PDF Upload')], max_length=20)),
                ('open_banking_connected', models.BooleanField(default=False)),
                ('open_banking_provider', models.CharField(blank=True, max_length=100)),
                ('open_banking_consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('open_banking_last_sync', models.DateTimeField(blank=True, null=True)),
                ('open_banking_accounts', models.JSONField(blank=True, default=list)),
                ('bank_statements', models.JSONField(blank=True, default=list)),
                ('company_documents', models.JSONField(blank=True, default=dict)),
                ('personal_documents', models.JSONField(blank=True, default=dict)),
                ('solicitor_firm_name', models.CharField(blank=True, help_text="Borrower's preferred solicitor firm name", max_length=255)),
                ('solicitor_sra_number', models.CharField(blank=True, help_text='SRA registration number', max_length=50)),
                ('solicitor_contact_name', models.CharField(blank=True, help_text='Primary contact at solicitor firm', max_length=255)),
                ('solicitor_contact_email', models.EmailField(blank=True, help_text='Solicitor contact email', max_length=254)),
                ('solicitor_contact_phone', models.CharField(blank=True, help_text='Solicitor contact phone', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(blank=True, to='documents.document')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_borrower_profiles', to=settings.AUTH_USER_MODEL)),
                ('solicitor_user', models.ForeignKey(blank=True, help_text='If solicitor is already a user in the system, link to their account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_solicitor_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
