# Generated by Django 4.1.13 on 2026-01-15 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdocumentlink',
            name='document_type_description',
            field=models.CharField(blank=True, help_text="Description or type of document (e.g., 'Site Visit Photos', 'Progress Report Week 4')", max_length=200),
        ),
        migrations.AddField(
            model_name='drawdown',
            name='ms_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawdown',
            name='ms_notes',
            field=models.TextField(blank=True, help_text='MS review notes and comments'),
        ),
        migrations.AddField(
            model_name='drawdown',
            name='ms_review_status',
            field=models.CharField(choices=[('pending', 'Pending MS Review'), ('under_review', 'Under MS Review'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_completed', 'Site Visit Completed'), ('ms_approved', 'MS Approved for Lender Review'), ('ms_rejected', 'MS Rejected')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='drawdown',
            name='ms_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawdown',
            name='ms_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Monitoring Surveyor who reviewed this drawdown', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ms_reviewed_drawdowns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dealdocumentlink',
            name='document_category',
            field=models.CharField(choices=[('compliance', 'Compliance (KYC/AML)'), ('legal', 'Legal'), ('reports', 'Reports'), ('financial', 'Financial'), ('drawdowns', 'Drawdowns'), ('drawdown_progress_reports', 'Drawdown: Progress Reports'), ('drawdown_photos', 'Drawdown: Photos'), ('drawdown_consultants_building_control', 'Drawdown: Consultants & Building Control'), ('drawdown_other', 'Drawdown: Other')], max_length=50),
        ),
    ]
