# Generated by Django 4.1.13 on 2026-01-15 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultants', '0001_initial'),
        ('documents', '__first__'),
        ('deals', '0002_dealdocumentlink_document_type_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('valuer', 'Valuer'), ('monitoring_surveyor', 'Monitoring Surveyor'), ('solicitor', 'Solicitor')], max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('viewed', 'Viewed'), ('quoted', 'Quoted'), ('declined', 'Declined'), ('expired', 'Expired')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('quote_due_at', models.DateTimeField(blank=True, help_text='Deadline for quote submission', null=True)),
                ('deal_summary_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of deal information visible to provider (redacted)')),
                ('lender_notes', models.TextField(blank=True, help_text='Internal notes from lender')),
                ('decline_reason', models.TextField(blank=True, help_text='Reason if declined by provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_enquiries', to='deals.deal')),
                ('provider_firm', models.ForeignKey(help_text='The consultant/solicitor firm this enquiry is sent to', on_delete=django.db.models.deletion.CASCADE, related_name='deal_enquiries', to='consultants.consultantprofile')),
            ],
            options={
                'verbose_name': 'Provider Enquiry',
                'verbose_name_plural': 'Provider Enquiries',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderStageInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('valuer', 'Valuer'), ('monitoring_surveyor', 'Monitoring Surveyor'), ('solicitor', 'Solicitor')], max_length=30)),
                ('current_stage', models.CharField(help_text="Current stage name (e.g., 'instructed', 'inspection_completed')", max_length=50)),
                ('stage_entered_at', models.DateTimeField(auto_now_add=True)),
                ('stage_history', models.JSONField(blank=True, default=list, help_text='History of stage transitions')),
                ('instructed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_stages', to='deals.deal')),
                ('provider_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_stage_instances', to='consultants.consultantprofile')),
            ],
            options={
                'verbose_name': 'Provider Stage Instance',
                'verbose_name_plural': 'Provider Stage Instances',
                'ordering': ['deal', 'role_type'],
            },
        ),
        migrations.CreateModel(
            name='ProviderQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('valuer', 'Valuer'), ('monitoring_surveyor', 'Monitoring Surveyor'), ('solicitor', 'Solicitor')], max_length=30)),
                ('price_gbp', models.DecimalField(decimal_places=2, help_text='Total quote price in GBP', max_digits=15)),
                ('lead_time_days', models.PositiveIntegerField(help_text='Estimated lead time in days')),
                ('earliest_available_date', models.DateField(blank=True, null=True)),
                ('scope_summary', models.TextField(help_text='Summary of services included in quote')),
                ('assumptions', models.TextField(blank=True, help_text='Assumptions and exclusions')),
                ('deliverables', models.JSONField(blank=True, default=list, help_text='List of deliverables included')),
                ('validity_days', models.PositiveIntegerField(default=30, help_text='Quote validity period in days')),
                ('payment_terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='submitted', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Quote version number')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_notes', models.TextField(blank=True, help_text='Internal notes from provider')),
                ('lender_notes', models.TextField(blank=True, help_text='Internal notes from lender')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='deals.providerenquiry')),
            ],
            options={
                'verbose_name': 'Provider Quote',
                'verbose_name_plural': 'Provider Quotes',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('valuer', 'Valuer'), ('monitoring_surveyor', 'Monitoring Surveyor'), ('solicitor', 'Solicitor')], max_length=30)),
                ('deliverable_type', models.CharField(choices=[('valuation_report', 'Valuation Report'), ('reliance_letter', 'Reliance Letter'), ('ims_initial_report', 'IMS Initial Report'), ('monitoring_report', 'Monitoring Report'), ('drawdown_certificate', 'Drawdown Certificate'), ('legal_doc_pack', 'Legal Document Pack'), ('cp_evidence', 'CP Evidence'), ('completion_statement', 'Completion Statement')], max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revised', 'Revised')], default='uploaded', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Review comments/notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_deliverables', to='deals.deal')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_deliverables', to='documents.document')),
                ('provider_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_deliverables', to='consultants.consultantprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables_reviewed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverables_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Provider Deliverable',
                'verbose_name_plural': 'Provider Deliverables',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('valuer', 'Valuer'), ('monitoring_surveyor', 'Monitoring Surveyor'), ('solicitor', 'Solicitor')], max_length=30)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('confirmed', 'Confirmed'), ('rescheduled', 'Rescheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='proposed', max_length=20)),
                ('date_time', models.DateTimeField(blank=True, help_text='Scheduled date and time', null=True)),
                ('location', models.CharField(blank=True, help_text='Appointment location/address', max_length=500)),
                ('notes', models.TextField(blank=True, help_text='Appointment notes/agenda')),
                ('proposed_slots', models.JSONField(blank=True, default=list, help_text='List of proposed time slots [{date_time, notes}]')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='User who confirmed the appointment (usually borrower)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_confirmed', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_appointments', to='deals.deal')),
                ('proposed_by', models.ForeignKey(blank=True, help_text='User who proposed the appointment (usually provider)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_proposed', to=settings.AUTH_USER_MODEL)),
                ('provider_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_appointments', to='consultants.consultantprofile')),
            ],
            options={
                'verbose_name': 'Provider Appointment',
                'verbose_name_plural': 'Provider Appointments',
                'ordering': ['date_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealProviderSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('valuer', 'Valuer'), ('monitoring_surveyor', 'Monitoring Surveyor'), ('solicitor', 'Solicitor')], max_length=30)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('lender_approval_required', models.BooleanField(default=True, help_text='Whether lender approval is required for this selection')),
                ('lender_approved_at', models.DateTimeField(blank=True, null=True)),
                ('acting_for_party', models.CharField(blank=True, choices=[('lender', 'Lender'), ('borrower', 'Borrower')], help_text='Required for solicitors: acting for lender or borrower', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_selections', to='deals.deal')),
                ('lender_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_selections_approved', to=settings.AUTH_USER_MODEL)),
                ('provider_firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_selections', to='consultants.consultantprofile')),
                ('quote', models.ForeignKey(blank=True, help_text='The quote that was accepted (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='deals.providerquote')),
                ('selected_by', models.ForeignKey(blank=True, help_text='User who made the selection (borrower or lender)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_selections_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deal Provider Selection',
                'verbose_name_plural': 'Deal Provider Selections',
                'ordering': ['deal', 'role_type'],
            },
        ),
        migrations.AddIndex(
            model_name='providerstageinstance',
            index=models.Index(fields=['deal', 'role_type'], name='deals_provi_deal_id_9dea98_idx'),
        ),
        migrations.AddIndex(
            model_name='providerstageinstance',
            index=models.Index(fields=['provider_firm', 'current_stage'], name='deals_provi_provide_bd205b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='providerstageinstance',
            unique_together={('deal', 'role_type', 'provider_firm')},
        ),
        migrations.AddIndex(
            model_name='providerquote',
            index=models.Index(fields=['enquiry', 'status'], name='deals_provi_enquiry_7e8156_idx'),
        ),
        migrations.AddIndex(
            model_name='providerenquiry',
            index=models.Index(fields=['deal', 'role_type', 'status'], name='deals_provi_deal_id_5b4530_idx'),
        ),
        migrations.AddIndex(
            model_name='providerenquiry',
            index=models.Index(fields=['provider_firm', 'status'], name='deals_provi_provide_254ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdeliverable',
            index=models.Index(fields=['deal', 'role_type', 'status'], name='deals_provi_deal_id_223b32_idx'),
        ),
        migrations.AddIndex(
            model_name='providerdeliverable',
            index=models.Index(fields=['provider_firm', 'status'], name='deals_provi_provide_15e2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='providerappointment',
            index=models.Index(fields=['deal', 'role_type', 'status'], name='deals_provi_deal_id_cfd6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='providerappointment',
            index=models.Index(fields=['provider_firm', 'date_time'], name='deals_provi_provide_e4c8af_idx'),
        ),
        migrations.AddIndex(
            model_name='dealproviderselection',
            index=models.Index(fields=['deal', 'role_type'], name='deals_dealp_deal_id_9c8482_idx'),
        ),
        migrations.AddIndex(
            model_name='dealproviderselection',
            index=models.Index(fields=['provider_firm'], name='deals_dealp_provide_4097e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dealproviderselection',
            unique_together={('deal', 'role_type')},
        ),
    ]
