# Generated by Django 4.1.13 on 2026-01-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_providerenquiry_providerstageinstance_providerquote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerenquiry',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When provider acknowledged they will quote', null=True),
        ),
        migrations.AddField(
            model_name='providerenquiry',
            name='acknowledgment_notes',
            field=models.TextField(blank=True, help_text="Provider's notes when acknowledging (e.g., timeline, questions)"),
        ),
        migrations.AddField(
            model_name='providerenquiry',
            name='expected_quote_date',
            field=models.DateField(blank=True, help_text="Provider's expected quote submission date", null=True),
        ),
    ]
