# Generated by Django 4.1.13 on 2026-01-16 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_providerenquiry_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerdeliverable',
            name='parent_deliverable',
            field=models.ForeignKey(blank=True, help_text='Previous version if this is a revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='deals.providerdeliverable'),
        ),
        migrations.AddField(
            model_name='providerdeliverable',
            name='version_history',
            field=models.JSONField(blank=True, default=list, help_text='History of all versions of this deliverable'),
        ),
    ]
