# Generated by Django 4.1.13 on 2026-01-16 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0005_providerdeliverable_parent_deliverable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealmessagethread',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_message_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealmessagethread',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, only explicitly added parties can see this thread'),
        ),
        migrations.AddField(
            model_name='dealmessagethread',
            name='visible_to_roles',
            field=models.JSONField(blank=True, default=list, help_text="List of roles that can see this thread (e.g., ['lender', 'borrower', 'valuer'])"),
        ),
        migrations.AlterField(
            model_name='dealmessagethread',
            name='visible_to_parties',
            field=models.ManyToManyField(help_text='Parties that can view and participate in this thread', related_name='accessible_threads', to='deals.dealparty'),
        ),
    ]
