# Generated by Django 4.1.13 on 2026-01-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_dealmessagethread_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerenquiry',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('acknowledged', 'Acknowledged'), ('preparing_quote', 'Preparing Quote'), ('queries_raised', 'Queries Raised'), ('ready_to_submit', 'Ready to Submit'), ('quoted', 'Quoted'), ('declined', 'Declined'), ('expired', 'Expired')], default='sent', max_length=20),
        ),
    ]
