# Generated by Django 4.1.13 on 2026-01-16 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
        ('deals', '0007_add_enquiry_workflow_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetric',
            name='provider_firm',
            field=models.ForeignKey(blank=True, help_text='Provider firm (consultant/solicitor) for provider-specific metrics', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='consultants.consultantprofile'),
        ),
        migrations.AddField(
            model_name='performancemetric',
            name='role_type',
            field=models.CharField(blank=True, choices=[], help_text='Provider role type (valuer, monitoring_surveyor, solicitor) for provider metrics', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='performancemetric',
            name='metric_type',
            field=models.CharField(choices=[('acknowledgment_time', 'Acknowledgment Time'), ('requisition_response_time', 'Requisition Response Time'), ('cp_satisfaction_time', 'CP Satisfaction Time'), ('completion_time', 'Completion Time'), ('stage_dwell_time', 'Stage Dwell Time'), ('task_completion_time', 'Task Completion Time'), ('quote_response_time', 'Quote Response Time'), ('quote_acceptance_rate', 'Quote Acceptance Rate'), ('deliverable_delivery_time', 'Deliverable Delivery Time'), ('deliverable_rework_count', 'Deliverable Rework Count'), ('appointment_lead_time', 'Appointment Lead Time'), ('time_to_completion_impact', 'Time to Completion Impact')], max_length=50),
        ),
    ]
